background #151217
foreground #e8e0e8
cursor #dcb9f8
cursor_text_color #3f2358
selection_background #4b454d
selection_foreground #cdc4ce

active_tab_background #dcb9f8
active_tab_foreground #3f2358
inactive_tab_background #4b454d
inactive_tab_foreground #cdc4ce

# Colores ANSI estándar (Base16 / Material You)
color0 #151217
color1 #ffb4ab
color2 #dcb9f8
color3 #f3b7bd
color4 #d1c1d9
color5 #6f5289
color6 #653a40
color7 #e8e0e8

